dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 1

      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER')}}"
      private_key: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      role: TRANSFORM

      database: DBT_CI_DEMO
      warehouse: COMPUTE_WH
      schema: SRC
      client_session_keep_alive: False
      query_tag: github_action_query
