name: dbt CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  DBT_PRIVATE_KEY: ${{ secrets.DBT_PRIVATE_KEY }}
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }} 

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dbt_project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install requirements
        #run: pip install dbt-core dbt-snowflake sqlfluff
        run: pip install -r requirements.txt

      - name: Debug working directory and files
        run: pwd
             ls -R

      - name: Check connection to Snowflake
        run: dbt debug --profiles-dir ./
      
      - name: Install dbt dependencies
        run: dbt deps

      - name: Run lint check
        run: sqlfluff lint models --dialect snowflake

      - name: Run dbt test
        run: dbt test --profiles-dir ./

      - name: dbt run
        run: dbt run --profiles-dir ./
        